security:
spring:
  session:
    store-type: redis
zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
      sensitive-headers:
logging:
  level:
    org.springframework:
      security: DEBUG
      session: TRACE